### ISSUE TITLE
Replace c++ keyword 'auto' with concrete type for better understanding at the examples 

### ISSUE THREAD

**Issue by SimeonEhrig** [ComputationalRadiationPhysics/alpaka#490] opened 2018-05-15 11:38 UTC
I think it is useful to replace the keyword `auto` with the concrete object type in the alpaka examples. The keyword `auto` is good for writing code but not for reading code, because information about used classes get lost and this not good for beginners.

For me, it was harder to use the doxygen documentation, because I didn't know the concrete classes, which I had to search after it.

**Comment by ax3l** [comment] 2018-05-15 11:41
@SimeonEhrig thank you for the report. I share your feeling that over-used `auto` in modern C++ does not add to understandably.

Can you maybe point to a specific example and on which lines you would as a new reader like to know the type?

**Comment by SimeonEhrig** [comment] 2018-05-15 17:25
I agree with Axel. At the helloWorld example kernel, alpaka::vec should be used, to show a beginner, that alpaka::vec will be used for "everything".

Same thing here:
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8aebeb42d063f4a3d2a25274d094ed44d156b21e/example/bufferCopy/src/bufferCopy.cpp#L338-L339

This lines of code are really problematic, because the return value in the doxygen documentation is just auto:
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8aebeb42d063f4a3d2a25274d094ed44d156b21e/example/vectorAdd/src/main.cpp#L129-L131
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8aebeb42d063f4a3d2a25274d094ed44d156b21e/example/vectorAdd/src/main.cpp#L141-L143 

Here, I think the raw pointer is better, than the `auto`, because it is more impressive. It shows the developer: "Hey, this is raw pointer. Be careful." I know, it's sounds really trivial, but every small hint can help, if you begin with a new framework (specially, if you are student in the lower semester ;-) )
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8aebeb42d063f4a3d2a25274d094ed44d156b21e/example/vectorAdd/src/main.cpp#L165

**Comment by ax3l** [comment] 2018-05-15 17:39
Of course for heavily duplicated long types we can also just add an expressive `using vec1D = alpaka::vec::Vec<alpaka::dim::DimInt<1u>, Idx>;` and use this short hand instead of an `auto`.

**Comment by BenjaminW3** [comment] 2018-05-16 09:40
In your first and last example I can fully understand that the real type would be better in an example.
The buffer `alloc` examples are not that easy. The problem is that the return type depends on the (template) parameters. The user of alpaka should never rely on the type returned by this method (it can change at any time) and should handle it as an opaque buffer handle.

**Comment by SimeonEhrig** [comment] 2018-05-16 11:43
In the BufferCopy you use the concrete type.
https://github.com/ComputationalRadiationPhysics/alpaka/blob/8aebeb42d063f4a3d2a25274d094ed44d156b21e/example/bufferCopy/src/bufferCopy.cpp#L252-L255

Alternatively, you can add a comment and describe that `auto` is the better return type, because the return type is really depend of the (template) argument. Additional you can name the unspecialized class. Adding a the description to the doxygen also would be possible.

The problem at this point is, you see `auto` is the value of the variable and  you can look at the doxygen and see the function return a value of the type `auto`. But you don't know what kind of object it is or why the alpaka-developer use `auto`.

**Comment by BenjaminW3** [comment] 2018-05-17 08:17
@SimeonEhrig You are partially right, in the bufferCopy example there is something that looks like a type.
```
alpaka::mem::buf::Buf<DevHost, Data, Dim, Idx> hostBuffer(alpaka::mem::buf::alloc<Data, Idx>(devHost, extents)); 
alpaka::mem::buf::Buf<DevAcc, Data, Dim, Idx> deviceBuffer1(alpaka::mem::buf::alloc<Data, Idx>(devAcc, extents)); 
```
However, this is not the real type. `alpaka::mem::buf::Buf` is an alias to the `alpaka::mem::buf::traits::BufType` trait which is specialized to the real buffer type depending on the template parameters. The user is allowed to use this "type" and we could use it in the examples but I am not sure if it really makes things more clear.

**Comment by SimeonEhrig** [comment] 2018-05-17 11:09
@BenjaminW3 
I would prefer `alpaka::mem::buf::Buf` because, my approach would be:
1. search after `alpaka::mem::buf::Buf` in the doxygen
2. see traits and search after it with google
3. see, that it is really complicated and auto is a good idea

With `auto`, I hope it will works every time and never throw in an error.

At the end, there will be no difference, if I know that is really complicated or don't know anything about it. But for my personal feeling as developer, it would be better if I could understand it (theoretically).

**Comment by ax3l** [comment] 2018-05-17 11:19
I think in this case just adding in the example a comment with a hint to the type (trait) would be sufficient. and then keep the `auto` as source.

**Comment by BenjaminW3** [comment] 2018-05-26 09:39
I have added types for all variable except the executors in #494.
Furthermore, I am removing the necessity to create an executor that is only used once in #499 and replace all example usages.
Therefore, everything from this ticket should be solved and I will close it.

**Closed by BenjaminW3** 2018-05-26 09:39 UTC
Labels: example, refactoring
