### ISSUE TITLE
change coding style

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#102] opened 2015-11-20 09:33 UTC
After locking more and more in the internal parts of `ALPAKA` I realized that it is very difficult to read the code do to the heavy template usage and the current code style.

This is a request to change the style a little bit and define coding guide lines

an example of the current code (not highlighted): 
```
template<
    typename TExtent,
    typename TBuf>
ALPAKA_FN_HOST static auto taskSet(
    TBuf & buf,
    std::uint8_t const & byte,
    TExtent const & extent)
-> mem::view::cuda::detail::TaskSet<
    TDim,
    TBuf,
    TExtent>
{
    return
        mem::view::cuda::detail::TaskSet<
            TDim,
            TBuf,
            TExtent>(
                buf,
                byte,
                extent);
}
```

**My suggestion is to**

tag = function/method or parameter name 
element = `)`, `}` , `<`, `>`, ... 

**function/ methods**

1. the opening element is always on a line with a *opening tag* and the last element of a line
-  put the *closing elements* like `)`, `}` or `>` always on a new line and aligned with the *opening tag* (not the *opening element*).
-  an *opening element*
- each type or param get it's own line. 
- the opening parenthesis of a method or function get it's own line (no change to the old style).
- the function/method prefix must placed on a separate line.
- the result type must placed on a separate line (sometimes the result is very long).
- the function/method name get it's own line ( currently it is hard to find a function name inside the code block).
- it is allowed to put a template definition with one argument on one line and ignore rule *1.*, *2.* and *3*
- trailing return type definition should used in C++11 `auto size() const -> std::size_t;` instead of `std::size_t size() const;`

All in all the rules should help to focus very fast function/ method names, result types and template signatures begin and end also if no IDE function name listing is available.

The first example than looks like:
```
template<
    typename TExtent,
    typename TBuf
>
ALPAKA_FN_HOST static 
auto 
taskSet(
    TBuf & buf,
    std::uint8_t const & byte,
    TExtent const & extent
)
-> mem::view::cuda::detail::TaskSet<
        TDim,
        TBuf,
        TExtent
   >
{
    return
        mem::view::cuda::detail::TaskSet<
            TDim,
            TBuf,
            TExtent
        >(
            buf,
            byte,
            extent
        );
}
```

**template argument naming**

- template names must begin with upper case `T` followed by a camel case name (e.g. `TExtent`, `TSizeOfFoo`)
- no spaces after or before the element `<` or `>` are allowed `Bar<Foo>`

**code comments**

- the commentary tag is `//`
- ANSI C comments are not allowed e.g `/* ... */`

- for the indention `four (4) spaces` must used.

**defining of types:**

- the type qualifier `const` is placed right hand of the type which should be const
-  `&` (reference) and `*` (pointer) must surrounded by **one** space
```
int const * byte;  //pointer to const int value
int const * const byte; //const pointer to const int value
int * const byte; //const pointer to int value
int * byte; //pointer to int value
int* byte; //NOT ALLOWED by the coding guide lines (missing spaces around `*`)
```

**namespace**

- nested names space are a not indented (Currently they are, the point is that it limits the space for real code to the 80 character limit. A typical namespace depth in `ALPAKA` is four namespaces`
- the open parenthesis of a namespace must placed on a separate line
- the closing parenthesis of a namespace must placed together with a namespace name as comment on a new line

```
namespace Foo
{
namespace Bar
{

} //namespace Bar
} //namespace Foo
``` 

**classes and structs**

- the rules from the point **function/ methods** hold here
- visibility definitions like `public`, `private` and `protected` for inheritance must placed inline with the parent class 
- in class `plublic:`, `private:` and `protected:` is not indented

```
template<
    typename TDim,
    typename TSize,
    typename TKernelFnObj,
    typename... TArgs
>
class ExecGpuCudaRt final :
    public Foo<
        TDim, 
        TSize
    >,
    private Bar<TKernelFnObj>
{
public:
    ALPAKA_FN_HOST
    ExecGpuCudaRt
    {
        dummyCall();
    }

    ALPAKA_FN_HOST
    void
    opertator()
    {
        ...
    }
};
```

**Comment by psychocoderHPC** [comment] 2015-11-20 09:35
@erikzenker and @BenjaminW3 
This is my first draft to define the coding guide line for ALAPKA. 
All points are open for discussion.

My goal is to have a definition before the first release and reformat the code.

**Comment by erikzenker** [comment] 2015-11-20 11:50
I reviewed the guideline and edited some typos and formulations.

There is nothing I can complain about in the scope of alpaka.

**Comment by psychocoderHPC** [comment] 2015-11-20 13:57
@axel, @bussmann and me discussed offline that we should use this discussion as base to merge all styles of the different projects in `ComputationalRadiationPhysics` to one.
My current description above describe some parts which are currently not defined in the [PIConGPU coding guide line](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Coding-Guide-Lines), some points are different e.g `PIConGPU` vs. `ALPAKA`
 - template naming `T_*` vs `T*`,
 - spaces inside function signatures `foo( bool x )` vs. `foo(bool x)`
 - usage of const declaration for types `const bool& x;` vs. `bool const & x;`

@ComputationalRadiationPhysics/picongpu-maintainers, @ComputationalRadiationPhysics/haseongpu-maintainers and @theZiz

**Comment by ax3l** [comment] 2015-11-20 14:12
yes, I think we should merge and publish them in one guideline for the whole CRP organization, starting with C++.

The files in the [PIConGPU wiki](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Coding-Guide-Lines) should be a good start; multiline template and parameter arguments as you define it here would be a good addition and are currently missing.

It would also be great if we could make changes only with generic "tools" users, but we did not find [sufficient automatic tools yet](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Coding-Guide-Lines#auto-testing-via-) (see our [first uncrustify try](https://github.com/ComputationalRadiationPhysics/picongpu/blob/71af8e8bf07d9fb36c33df561cc1f796133fc16f/doc/picongpu_uncrustify.cfg)).

**Comment by bussmann** [comment] 2015-11-20 14:18
Asbolutely!

Am 20.11.2015 um 15:12 schrieb Axel Huebl:

**Comment by ax3l** [comment] 2015-11-20 14:30
to answer some questions:

> single parameters (in same line)

use at least spaces such as `Bar< Foo >`

> for the indention four (4) spaces must used. Should we switch to one tab?

no, that sucks because each editor displays them differently.
fixes space rules are easy to configure.

**Comment by theZiz** [comment] 2015-11-20 14:43
I don't see a problem, whether an editor shows 2, 4 or 8 spaces per tab. It is as hard to configure the shown tab-width as 4 spaces as to configure the editor to directly use 4 spaces instead of tab.
However I just noticed, my editor is able to guess the indention behaviour for a source file. So it will in fact not affect me very much. I still prefer one tab indention.

**Comment by psychocoderHPC** [comment] 2015-11-20 14:49
The space vs. tab problem is not related to our own IDE. The point is if you go for example to a new system our you take a look in your code on the screen of someone else than the code looks different on each IDE.
If the code look not equal it is hard to read code whether you wrote it by your self.

After thinking about the problematic I vote for indention with four spaces. (4 spaces 4 ever^^)

**Comment by ax3l** [comment] 2015-11-20 14:52
agreed, also with the inflationary use of newlines one can spare 4 spaces. (less spaces give me real trouble reading stuff.)

**Comment by BenjaminW3** [comment] 2015-11-20 14:56
Thanks for writing this! Most of the points are totally valid!
However, I have some remarks:
- `the closing parenthesis of a namespace must placed together with a namespace name as comment on a new line`:
I am totally against this. Such things always tend to get out of sync with real code and should be provided by the IDE/Editor.
- I would move the `auto` of the function declarations onto the same line as the `ALPAKA_FN_HOST static ` because it does not add anything. 
- `is is allowed to put a template definition with one argument on one line and ignore rule 1., 2. and 3`: I do not know if such exceptions really help.
- `ANSI C comments are not allowed e.g /* ... */` Currently this is inconsistent because the license header uses them.
- Could you please add a note that trailing return types always have to be used? (at least for alpaka)

**Comment by ax3l** [comment] 2015-11-20 15:02
> I would move the auto of the function declarations onto the same line as the ALPAKA_FN_HOST static because it does not add anything. 

I think the idea here is to be C++98 compatible with the same rule, and I think that is ok.

**Comment by psychocoderHPC** [comment] 2015-11-20 15:03
@BenjaminW3 
I missed to say that the code style should also valid for C++98 and C. Therefore the result type has it's own line to avoid
```
template< 
    typename TDim, 
    typename TFoo,
    typename TBar
>
ALPAKA_FN_HOST static const DataSpace<
    TDim,
    TFoo,
    TBar
>
    ExecGpuCudaRt(...)
```

**Comment by ax3l** [comment] 2015-11-20 15:06
btw, should `/* ....*/` comments end on a new line
```c++
/* like this
 * comment?
 */
```

and btw, doxygen should be `/** ...*/` only? And what about the second line, isn't the intent changing there?
```c++
/** huh, ...
 * one char earlier, ha
 */
```

**Comment by theZiz** [comment] 2015-11-20 15:08
I don't get the point. So the code looks different. This is a benefit, not a problem! The user can choose, what (s)he likes more. E.g. I used to develop on my netbook (800x480!) from time to time, where 1 tab = 2 spaces. But at a bigger screen I can use 4 spaces tab width again.
However I am fine with 4 spaces (but still vote for one tab :P), but imho your mentioned argument is invalid.

PS: We are discussing tab vs. spaces in room 325 right now. Feel free to join our incredible productive discussion! ;)

**Comment by ax3l** [comment] 2015-11-20 15:09
you forgot the "a browser TAB will leave the `<input>` element, argument" ;)

**Comment by ax3l** [comment] 2015-11-20 15:10
> I missed to say that the code style should also valid for C++98 and C.

why `C`? makes no sense, imho.

**Comment by psychocoderHPC** [comment] 2015-11-20 15:11
I added a trailing return rule.

**Comment by psychocoderHPC** [comment] 2015-11-20 15:12
@Axel The rules should also compatible with `C` if we start a `C` project in CRP.

**Comment by ax3l** [comment] 2015-11-20 15:16
we will not *start* ne C projects, we will continue add to existing projects in C with existing styles (adios, brotli, cuda_memtest)

**Comment by psychocoderHPC** [comment] 2015-11-20 15:18
@room325 Please post your offline discussion results here!

**Comment by BenjaminW3** [comment] 2015-11-20 16:05
`not clearly written, he means: only use /* ... */ and no //`
I think that psychocoderHPC meant what he wrote.
I do not see any advantage in using C-style comments (`/*...*/`) over C++ style (`//`) ones. Furthermore, you are able to uncomment a function containing C++-style comments with C-style ones for e.g. debugging while you can`t do it when there are C-style comments in the function.

**Comment by BenjaminW3** [comment] 2015-11-20 16:07
I have the same opinion as @theZiz.
Tabs are better then spaces because everyone can have the indendation level he wants without having to influence the others only by changing his editor settings.
However, I can live with 4 tabs.

**Comment by psychocoderHPC** [comment] 2015-11-20 16:08
@benjamin: there is a typo in your last comment `I can live with 4 tabs.` -> `I can live with 4 spaces`

**Comment by BenjaminW3** [comment] 2015-11-20 16:17
True :smile:

**Comment by erikzenker** [comment] 2015-11-20 16:44
Vote for `@param`

**Comment by f-schmitt-zih** [comment] 2015-11-20 17:23
Don't use tabs! :) some companies even send out automatic emails for
checkins titled: "You are a tab offender"

**Comment by bussmann** [comment] 2015-11-20 20:08
What @f-schmitt-zih said.

**Comment by psychocoderHPC** [comment] 2015-11-20 21:24
What is with a rule to put operators like `,`, `+`, ... at the beginning of a line.
As I wrote this I see that it looks ugly with the current defined indention but I would like to add a rule for using suffix or postfix operators.
Or should we use `,` always as postfix operator but math operator's like `-`, `+` as suffix operators. 

**example from the top with `,` as suffix operator***
```
template< 
    typename TExtent
    , typename TBuf
>
ALPAKA_FN_HOST static 
auto 
taskSet(
    TBuf & buf
    , std::uint8_t const & byte
    , TExtent const & extent
)
-> mem::view::cuda::detail::TaskSet<
        TDim
        , TBuf
        , TExtent
   >
{
    return
        mem::view::cuda::detail::TaskSet<
            TDim
            , TBuf
            , TExtent
        >(
            buf,
            , byte
            , extent
        );
}
```

**math equation**
```
const float factor = charge * charge
    / (
        6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass
    );
```

or
```
const float factor = charge * charge / (
    6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass
);
```

**Comment by psychocoderHPC** [comment] 2015-11-20 21:38
For doxygen I found that C++ comments only  interpreted if three slashes `///` are used https://en.wikipedia.org/wiki/Doxygen

I can't find any negatives or positives about using `@` or `\` for doxygen comments.

**Comment by psychocoderHPC** [comment] 2015-11-20 21:42
Using ANSI C `/* ... */` or C++ `//` comments.

A older version of the `nvcc` compiler could not handle `//` comments correct.
```
void 
foo(
    bool bar, // this is bar
    bool bar2 // more bar variables 
){};
```

**Comment by BenjaminW3** [comment] 2015-11-21 06:35
or
```
const float factor =
    charge * charge /
    (6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass);
```

or

```
const float factor =
    charge * charge
    / (6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass);
```

or (because it is no assignment but a definition)

```
const float factor(
    charge * charge
    / (6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass));
```

or C++11

```
const float factor{
    charge * charge
    / (6.0 * PI * EPS0 * c2 * c2 * SPEED_OF_LIGHT * mass * mass)};
```

I would prefer the last version with mathematical operators at the begin of the line.
However, I prefer commas to be at the end of the lines.

As can be seen in both versions I do not think that the parantheses within expression (which are only there to define the precedence) should be part of the newline rules.

**Comment by BenjaminW3** [comment] 2015-11-21 06:37
`A older version of the nvcc compiler could not handle // comments correct.`
This is no argument for C comments anymore because those nvcc versions are antique and now unsupported.

Doxygen also supports `//!` as alpaka is using and also some more other styles for C++ comments.

**Comment by BenjaminW3** [comment] 2015-11-21 07:09
All in all I am not sure if unifying all aspects of the coding guidelines over so many projects would be a good idea.
alpaka is very special in that it consits only of template specializations and few algorithmic things. Therefore, the template parameters and template types are really important. Furthermore, it is C++11 only and uses trailing return types everywhere.
picongpu on the other hand is much mor 'user' facing. The important parts are the algorithms/physics.
I think that special patterns at different hierarchy levels require adapted styles. Things like the indentation level should be unified but the trailing return type/auto handling are clearly alpaka specific.

**Comment by theZiz** [comment] 2015-11-21 14:03
@psychocoderHPC: You asked us to post the results of the discussions in room 325 here, so I will (although I am not sure, whether this still makes sense, but as every computer scientist I love internet discussions).

So the big argument (in room 325) against tabs was, that stuff like
`<tab>variable = something`
`<tab>         + something`
`<tab>         + something;`
would result in a very ugly mix of tabs and spaces. The counter argument was, that I would not choose such a code layout anyway, because if I change the name of variable e.g. to m_variable, I need to add two spaces for evers following line. I prefer this approach:
`<tab>variable = something`
`<tab><tab>+ something`
`<tab><tab>+ something;`
or
`<tab>variable = `
`<tab><tab>something +`
`<tab><tab>something +`
`<tab><tab>something;`
or some other similar approach.

We also made the not so serious suggestions to make a comment under the variable to clarify, that there shall be spaces and no tabs:
`<tab>variable = something`
`<tab>/*    */ + something`
`<tab>/*    */ + something;`
Tbh I like this approach. We even thought about using the free room for some ASCII art... If the variable name is long enough and many "somethings" are added, a whole explanation of the code could fit there. ;)

**Comment by ax3l** [comment] 2015-11-21 20:08
just to make clear, since tabs do not mix with spaces of any kind, look
different on different editors even with monospace fonts enabled, will
not work with ascii-art prettyness and do not work in web-based editors:
I will always vote against tabs and this is nothing people did not find
out in the last 40 years of programming already.

So focus on the interesting parts pls, this is boring and unproductive.

**Comment by BenjaminW3** [comment] 2015-11-21 20:30
`since tabs do not mix with spaces of any kind`
This is logical. However, they are not intended to be mixed as a mean of indendation, they are a replacement.

`look different on different editors even with monospace fonts enabled`
That is the main feature of tabs... Everyone can have them the size they want them to be.

`will not work with ascii-art prettyness`
That is not the use-case of tabs. Ascii-art will be within comments where spaces can be used. Tabs on the other hand are for indendation. Two completely different areas.

`do not work in web-based editors`
The only valid argument.

**Comment by ax3l** [comment] 2015-11-22 11:49
> `look different on different editors even with monospace fonts enabled`
> That is the main feature of tabs... Everyone can have them the size they want them to be.

What one consideres a "feature" is rather bad for other people. The typical scenario is: Rene is giving help to someone like 10x a day. If everyone is then "oh, let me quick change my 2 space tabs to 4 spaces" and "oh, too bad the web view is set to 1 space" this is just super annoying. Be aware that some people see this "feature" in rather the opposite.

> `do not work in web-based editors`
> The only valid argument.

Which is enough for not doing it.

Also, it's not backwards compatible to the styles we already use in PIConGPU (which was, btw., for every project around it a starting point and was simply ignored ;) ). The only extension we need is as @psychocoderHPC proposed the multiline arguments.

**Comment by psychocoderHPC** [comment] 2015-11-22 12:16
Please focus on the other rules and give feedback for currently missed descriptions.

Spacing question is now marked as solved :-)

**4 spaces for indentions**

**Comment by ax3l** [comment] 2015-11-22 20:04
> What is with a rule to put operators like ,, +, ... at the beginning of a line.
> As I wrote this I see that it looks ugly with the current defined indention but I would like to add a rule for using suffix or postfix operators.
> Or should we use , always as postfix operator but math operator's like -, + as suffix operators.

I personally like them as last operator since this clearly indicates a line continuation (as your example 2/3 above) and upcoming blocks, e.g., brackets, can be grouped the same way as you propose it already.

**Comment by ax3l** [comment] 2015-11-22 20:07
regarding comments: I think mixing `//` which is single-line comment ("C++") and `/* ... */` which is clearly multi-line comment is totally fine.

**Comment by ax3l** [comment] 2015-11-22 20:27
Besides all the style questions, @psychocoderHPC forgot to write some very important technical issues that we discussed offline. So let me summarize:

- styles should be **easily writable** on every editor (unconfigured `vi` over `nano` over `gedit` over the default GitHub browser editor to IDE's and full flavoured `vim` suites and VS or netbeans)
- styles should **look the same** in each of them, because we spend a lot of time running around and fixing/discussing code on each others computers and use various displaying engines from terminals to IDEs to GitHub
- must make sense **without colouring**
- they need to be as simple as possible, so we can (and really should only) use **tools** to auto-format, because our time is to costly to spend it on "oh you forgot to indent your namespaces" during reviews (scripts or monkeys must take that job)

and very, very important we need a **linter** that is
- deterministic:
  - calling it twice on the same input should get the same result
  - calling it twice, first on the code and second on the first-linted code, **must not** change it any more (e.g., uncrustify did change it again and again...)
- open source (of course)
- easily installable (e.g., should be a simple download or ideally in distros; linux/osx/windows)
- scriptable (of course, for travis and git pre-commit hooks)

Without those properties on the linter we can not add automated pre-commit hooks and CI remarks. And without tools it's again a waste of time, especially for the reviewers.

**Comment by psychocoderHPC** [comment] 2015-11-22 20:30
Note: I checked the C++ standard and both comment tags are allowed.
`//` is C++ and `/* */` is C++ too.

For multiline comments we should use the multiline tag und for a single line comment `//`.

**Comment by ax3l** [comment] 2015-11-22 20:37
agreed, I like that.

btw, I am also with @BenjaminW3 to remove out `} /* namespace-name */` rule. I like that but it's too tedious to update the same name twice in refactorings (same argument as `pragma once` vs. include guards).

**Comment by ax3l** [comment] 2015-11-22 20:40
also for comments:

I would add a space after `/* ` and `// ` for cosmetic reasons, somehow makes reading text way easier, imho.

**Comment by psychocoderHPC** [comment] 2015-11-22 20:40
@ax3l If we look only to the ruled at the top there is no known tool available which can handle them :-(
Uncrustify is as I know the tool with the most options but ist has only two or three rules for templates.

**Comment by ax3l** [comment] 2015-11-22 20:41
then we need one, because I don't want to life in a world of pedantic "I don't understand your code but let me point out your style is wrong by one space" contributions.

**Comment by bussmann** [comment] 2015-11-22 20:47
Let me add one more reason to unify coding style as much as possible:

When your codes live on as intended, they may live longer than you'll maintain them, be it because you left, got bored or started smth new.

Whatever happens, we'll hopefully be there to take care of the code as we do now.

And "we" here will mean René, most probably. Which means he'll have to deal with most of your codes, while you mostly deal with your own.

If I would be René, I'd appreciate a single style I could live with rather than having to cope with a botanical garden full of beauty and diversity - though the look might be awesome, it all comes down to a lot of hard work in the dirt to keep it that way.

**Comment by psychocoderHPC** [comment] 2015-11-22 20:56
To the point with the comment of the end of a namespace.
Please open [this file](https://github.com/ComputationalRadiationPhysics/alpaka/blob/master/include/alpaka/acc/AccCpuOmp2Threads.hpp) in your editor ( best with vi or nano) jump to the middle and go to the next namespace end. You can't tell which namespace end it is.
This file is not a bat implementation it shows a "problem" in template meta programming. Each trait must specialized in the namespace of the trait which lead's in many nested namespaces. This is extrem hard to read because if you find a namespace end you must go up to the definition.

Namespace indention helps a little bit in this case but the problem of namespace indention is that you go easily over the 80 character limit per line because we had deep namespaces structures in your libraries and programs. 

We should also take a look to the boost library the had the same problems, deep namespace structures and heavy template usage.

**Comment by ax3l** [comment] 2015-11-22 22:38
how does boost solve that readability problem?

**Comment by theZiz** [comment] 2015-11-22 22:52
If you look e.g. in the boost/mpl/unique.hpp the "always there" namespaces boost and mpl and in in line (`namespace boost { namespace mpl {` and closed at the end of the file without further comment (`}}`), but more unique namespaces are introduced one per line and commented with // namespace name like `namespace aux {` and `} // namespace aux`. However namespaces seem not to be indented at all, too.

(However they are not very consistent, some include files have `namespace aux`in the same line as boost and mpl, too.)

**Comment by erikzenker** [comment] 2015-11-23 08:26
I like to comment on closing namespaces, just to be clear where this closing bracket is coming from.
Maybe we should not force the existence / non existence of these comments, but if someone wants to use them it will be tolerated.

**Comment by ax3l** [comment] 2015-11-23 08:38
comment by @psychocoderHPC can probably be added axiomatically buy a simply regex.

**Comment by ax3l** [comment] 2015-11-23 08:48
regarding mathematical expressions:
I think all operations can simply put on the same line until it is full. line-continuation via operators requires the next operator to be the last part of the previous line (as written above). blocks, defined by brackets, should be aligned correctly.

```c++
a = 17.5 * L(n) + 18.123 * whenDoIreach80Chars *
    (
      ...
    ) +
    (
      ... /
      (
        ...
      )
    );
```

**Comment by psychocoderHPC** [comment] 2015-11-24 17:28
There is the [first draft](https://github.com/ComputationalRadiationPhysics/contributing) available.

Please follow the new discussion in https://github.com/ComputationalRadiationPhysics/contributing/issues/2.

**Comment by BenjaminW3** [comment] 2015-11-24 17:35
As there is a new thread, I will close this one.

**Closed by BenjaminW3** 2015-11-24 17:35 UTC
Labels: question
