### ISSUE TITLE
static_assert at sharedMem test  failing with MSVS

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/alpaka#444] opened 2017-11-10 17:26 UTC
I did not have any experience with alpaka (only read papers) and yesterday decided to try it hands-on. I took the develop branch since saw more recent commits there. First i did not have Boost libraries compiled for the right version of Visual Studio and so commented out tests in the main CMakeLists.txt file and got only alpaka itself and examples. It all went very smoothly for MSVS 2017 in Win32 and OpenMP 2.0 backend, examples are running and everything is fine. So this part was very nice and quick to do.

However, later i decided to do things properly, recompiled Boost and built the default configuration of alpaka with the tests using the same MSVS 2017 and Win32 setup. The sharedMem test fails to build with two static_asserts in Copy.hpp failing: [first](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cpu/Copy.hpp#L77-L79) and [second](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/mem/buf/cpu/Copy.hpp#L80-L82). It happens for T=alpaka::acc::AccCpuSerial<std::integral_constant<::size_t,1>,int>,
1>, TFnObj=SharedMemTester<TnumUselessWork,int32_t> in the test body and            TViewDst=alpaka::mem::buf::BufCpu<int32_t,std::integral_constant<::size_t,1>,int>, TViewSrc=std::vector<int32_t,std::allocator<int32_t>>, TExtent=int in the TaskCopy instance causing the static_asserts to fail.

There might be similar issues with other tests, but it got a bit complicated to investigate further. Something bad happens to my Visual Studio during the build process and after some time it just stops the build with "ran out of heap memory" message and then becomes close to unusable until system reboot. I assume that is not an issue of alpaka, but rather me messing smth up with building Boost or issue of MSVS itself. Meanwhile the examples did build really quickly and without any problem.

Now i also tried to reproduce it on the latest revision of master branch, but got other issues there. These might be on my side, need to take a closer look.

**Comment by BenjaminW3** [comment] 2017-11-10 20:38
Thanks for your report.
With the given information, I can not reproduce the errors you see. It works for me locally as well as in the CI. Which Visual Studio Version do you have? In the CI we have `Visual Studio 2017 version 15.4` with the compiler identifying as `19.0.24215.1`.

**Comment by BenjaminW3** [comment] 2017-11-10 21:13
The `out of heap memory` issue can be triggered by the alpaka tests. The test code is very template heavy (because it tries to test every possible combination of backends/ value types) and Visual Studio is not good in compiling it. The CI machines with only 4 GB of RAM sometimes have this issue as well.

**Comment by sbastrakov** [comment] 2017-11-10 21:56
I have Visual Studio 15.4.3, cmake identifies compiler as 19.11.25547.0. About memory - thanks for clarification, i was doing all this on a not really powerful laptop.

Btw these static_asserts do not fail for x64, but can't check all tests now due to memory issues.

**Comment by BenjaminW3** [comment] 2017-11-11 06:51
Ah, the 32 bit was the missing information. We do not currently have any 32 bit automatic testing. I do not know anybody who is using a 32 bit toolchain. For linux there is no reason to use 32 bit these days and for Windows we simply expected nobody to use it as well.
I will have a look at the failing tests.

**Comment by BenjaminW3** [comment] 2017-11-11 08:06
Further investigation results:
* The 32 bit Microsoft compiler can not compile some of the tests. It simply exhausts the whole 4 GB of memory space. So this is not necessarily Machine specific but a general incompatibility.
* the `sharedMem` example really triggers those `static_assert`s. I will try to fix this.

**Comment by psychocoderHPC** [comment] 2017-11-11 08:28
If a 32bit fix needs precompiler ifdefs or hacks please do jot fix it.
32bit platforms are not the target auf alpaka.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sbastrakov** [comment] 2017-11-11 08:38
I also pretty much never really use Win32 in MSVS, that just happened kinda randomly as i accidentally compiled Boost.Test for Win32 at first. Thanks for quick intestigation!

**Comment by psychocoderHPC** [comment] 2017-11-17 10:11
32bit compile should be fixed with #445

**Closed by psychocoderHPC** 2017-11-17 10:11 UTC
