### ISSUE TITLE
tests: cmake error

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/alpaka#422] opened 2017-10-19 09:00 UTC
If I try to build the tests I get the following error from CMake:

```
...
-- ALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLED
-- ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED
-- ALPAKA_ACC_GPU_CUDA_ENABLED
-- Configuring done

CMake Error: Files to be generated by multiple different commands: "test/analysis/headerCheck/CMakeFiles/headerCheck.dir/src/acc/headerCheck_generated_AccCpuFibers.hpp.cpp.o.cmake"
-- Generating done
-- Build files have been written to: buildAlpaka
```

In my case `ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE` is `OFF`.

Used CMake: 3.7.2

**Comment by BenjaminW3** [comment] 2017-10-19 09:21
This is a duplicate of #364.

**Closed by BenjaminW3** 2017-10-19 09:21 UTC
Labels: bug, testing
